### PR TITLE
List and filter sheets

### PR DESCRIPTION
**Pull request by aswansyahputra**
Hi,

I propose a functionality to filter excel sheets by using wild card or regular expression. For example:

```r
excel_sheets(readxl_example("datasets.xlsx"))
#> "iris"     "mtcars"   "chickwts" "quakes"  
excel_sheets(readxl_example("datasets.xlsx"), glob = "??i*")
#> "iris"     "chickwts"
excel_sheets(readxl_example("datasets.xlsx"), regexp = "(r|e)s$")
#> "mtcars" "quakes"
```

The purpose is to make it easier for user to pick certain sheets to be read simultaneously using `lapply()` or `map()`. Any suggestion is much appreciated!

Regards,

Aswan

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks! I can't quite decide how I feel about this.

I'll articulate the side of me that resists it: this feels like a result that is fairly easy for the the user to get via composition already. I.e. use `excel_sheets()` to get the names, then (say) pipe that to a regex filtering call, then pipe that into an iterative machine calling `read_excel(sheet = ...)`. So, why add arguments to existing functions when you can achieve the same by composing simple things?

What do you think? Do you have specific compelling example that helps us talk about this?

Even if my view prevails, you could develop such an example into a docs contribution somewhere in the package (help, workflow vignette, mini-vignette).

**Comment by aswansyahputra** [comment]
Thanks for you response!

I agree that we can post-process the output of `excel_sheets()` in an easy way. But, in my opinion `excel_sheets()` shares similar idea with `list.files()` or `fs::dir_ls()` so that adding a filtering arguments to it seems to be natural. What do you think?

**Comment by jennybc** [comment]
I think there are probably individual people and problem domains where the need to filter worksheets programmatically comes up a lot. And I gather this is true for you. But I don't think it's a very common need and it's easy to address via function composition. Hence my resistance.

**Comment by aswansyahputra** [comment]
Yes I think your reasoning is true. I will close this PR then.

I truly appreciate your feedback on this, thanks!

**Comment by jennybc** [comment]
This would still be very welcome as a mini-vignette. I like to help capture these common patterns, without necessarily building new functions and arguments into readxl itself.

Example of a mini-vignette on dealing with multiple header rows: https://readxl.tidyverse.org/articles/articles/multiple-header-rows.html

**Pull request closed without merging**
