### PR TITLE
Avoid infinite loop in `XlsWorkSheet::loadCells`

### PR DESCRIPTION
**Pull request by vkapartzianis**
I had a quick look at issue #373 at the invitation of a colleague. The code definitely enters an infinite loop with the samples provided, so I've tried and avoid that.

### CODE REVIEW

**Comment by jennybc** [comment]
Are you game to add a test and test sheet?

**Comment by vkapartzianis** [comment]
The test file is ~6MB, is that OK?

**Comment by jennybc** [comment]
Ooh no. Is that necessary? Sorry my mind is elsewhere but wanted to catch while your head was in right place, in case you can easily add test case.

**Comment by vkapartzianis** [comment]
OK, I've tried to simplify the test case. It seems it boils down to just an XLS spreadsheet with 65536 rows.

This request doesn't resolve the real problem, in addition. I'll work on it some more.

[65536-rows.zip](https://github.com/tidyverse/readxl/files/1636985/65536-rows.zip)

**Comment by jennybc** [comment]
> OK, I've tried to simplify the test case. It seems it boils down to just an XLS spreadsheet with 65536 rows.

Interesting. I've battled a few other cases of short vs long int in libxls. I mean, it's possible that I created this one. Or not.

**Comment by vkapartzianis** [comment]
I've added another commit. It should handle all 65536-row cases and it includes a simple test.

Note that this should be a problem with XLS files only. XLSX sheets aren't limited to 65536 rows as far as I can tell.

**Comment by jennybc** [comment]
Moving this to #432

**Pull request closed without merging**
