### PR TITLE
read_excel reads from URL, part of #278

### PR DESCRIPTION
**Pull request by MichaelChirico**
Basic idea's done. My approach is to augment `check_file` to more flexibly detect a URL if `!file.exists(path)`.

Use of `assign` to overwrite `path` is a bit wonky but I couldn't see how else to do it without rewriting `check_format` to return both the updated `path` and the inferred format. I considered re-factoring everything but a quick/logical way of doing so didn't come to me right away.

I am not clear why `read_excel_` goes through `check_file` again, given that it's a hidden function and `check_file` should always be run by the time `read_excel_` is. If we drop the `check_format` from `read_excel_`, we could skip the `assign('path')` kludge since it only exists to avoid downloading the file again at this juncture.

As far as testing, I don't know what's the proper way to test reading from a URL, so I didn't go too crazy and only added one test. It's self-referential, which feels... risky, but I weighed that against the option of picking some Excel file "in the wild" and hoping the file remains there in perpetuity; current implementation seems better than that, but I'm open to ideas.

Also open to using an `option` to change the `verbose` behavior of the file download, or setting the default to `FALSE`.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Just down to a Codecov failure. Can add tests as needed, just not sure the right way to do so for this case.

**Comment by jennybc** [comment]
Thanks for this! I am refactoring the pre-processing of `path` more generally, so just a heads up that this may get swept up into the larger effort (#454). Regardless, I'll certainly acknowledge your effort to things moving on this front.

**Comment by MichaelChirico** [comment]
@jennybc cool. happy to help hammer this into the redesign if you think it makes sense to delegate; just let me know.

**Comment by jennybc** [comment]
Thanks again. I've decided to hold off on handling URLs for this release. Notes on my thinking are [here](https://github.com/tidyverse/readxl/issues/278#issuecomment-381720113).

**Pull request closed without merging**
