### PR TITLE
Add param for number of rows used when guessing col_types. Implements #131

### PR DESCRIPTION
**Pull request by tklebel**
I gave #131 a shot. 
- Re-Rccp
- new param `n` including documentation, which passes `n` for `.xls` and `n_max` for `.xlsx` up to `read_excel`

``` r
# read 500 rows to determine col_types
read_excel("file.xlsx", n = 500)
```
- Updated tests:
  - Changed `types.xlsx`.
    - The first column has now 102 rows, all numeric.
    - Added new column `string_at_102` which contains `"ab"` at row 102.
  - added tests for correct `column_types`, `expect_warning` for `n = 100` and `expect_silent` for `n = 102`

### CODE REVIEW

**Comment by hangtime79** [comment]
Thomas, 
I was able to download, compile, and test your code. I tested with a spreadsheet that has been giving me issues with a column with mixed data types and your code appears to be working.

image


The response column included characters but they were not found until you got to row ~6000. Great work! Thank you.

Question is n_max just the same parameter for the number of rows to test against xlsx vs n for xls or is it something else?

**Comment by tklebel** [comment]
@hangtime79 the naming of the parameters internally is not very clear right now. Indeed, at some point `n_max` is used for .xlsx and `n` for .xls. If you dig deeper, they both point to `n_max` in the end.

For you it doesn't matter, since you would be using `read_excel("file.xls/x", n = 6500)` for both cases. Please tell me if that is how you used it, since that is how it was intended. Maybe my message above was a bit confusing.

@hadley I tried to stick with the names which I found in your code. Ultimately I think you should decide, how the params are named and where to make the switch from `n_max` to `n` (or any other name you would prefer for this param).

**Comment by bhive01** [comment]
I think I prefer to have the option to define how many rows before guessing the type to just setting a value, with some sort of sensible value. @hadley recently updated readr to do 1000 rows before guessing, and I just did a pull to align readxl with this value. 
https://github.com/hadley/readxl/pull/143

Like I said, it'd be better to have a reasonable default (1000?), but allow user definition like this pull.

**Comment by hangtime79** [comment]
@bhive01 I agree a 1000 rows is much more reasonable as per #143 but in the case of large sheets with sparse data, this particular option is incredibly valuable and doesn't impact performance of the larger population. In this case, user definition is the key. What @tklebel was able to do makes life much easier as it means you don't have to devolve into setting the data types of 80 columns in the case of some of my sheets. That's more coding on the part of the project and more on the part of the individual user.

**Comment by bhive01** [comment]
I'm with you ( @hangtime79 ) and @tklebel  then. 1000 row default like `readr` and allowing user definable max at the expense of increased computation time for huge sheets. I prefer `nmax` for a variable name to `n` as it takes into account a possible `n < nmax` situation.

**Comment by hangtime79** [comment]
Looping back in as this was discussed in #112. @tklebel completed this three months ago. Hoping @hadley will get a chance to act on this pull request soon. Until then those who need it can use @tklebel version.

**Comment by torbjorn** [comment]
Is there any reason why this feature change needs to take a year to complete?

**Comment by torbjorn** [comment]
And not sure if this has been covered, but why not allow all lines to be read before guessing the type? perhaps with n=-1 or n=0?

**Comment by jennybc** [comment]
Will live on in #257.

**Pull request closed without merging**
